default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  
test:
  <<: *default
  database: db/test.sqlite3

# development:
#   adapter: mysql2
#   encoding: utf8
#   database: socialteach
#   username: root
#   password:
#   host: 127.0.0.1
#   port: 3306
