development:
  adapter: sqlite3
  pool: 5
  timeout: 5000

# development:
#   adapter: mysql2
#   encoding: utf8
#   database: socialteach
#   username: root
#   password:
#   host: 127.0.0.1
#   port: 3306
