# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e605d161e86b9b2094faa0d0d1f0b53fd5ebbcd0049e09f6ba00c056034227a43bc3d587d5fe82ee53b84c9d9f63cc8674358a19299dc2eeea661a00388486c

test:
  secret_key_base: 78e37e71a50c5480ef5ac431e42e8d5ae7d75c83d299508ae42c69fa998bd6741835c812de02fbfba3879dd1c35bf2cc43f19c2734f51b20d47798358d1a7fb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
